repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff
        name: Ruff Lint
        args: [--fix]
      - id: ruff-format
        name: Ruff Format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        name: mypy Static Checker
        args: [--config-file, ./api/pyproject.toml, ./api]
        pass_filenames: false
        additional_dependencies:
          - fastapi
          - python-multipart
          - httpx
          - pymilvus
          - openai
          - sentence_transformers
          - pymupdf
          - pymupdf4llm


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml

  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: pytest --rootdir=api -v --maxfail=1 --disable-warnings
        language: python
        pass_filenames: false
        types: [python]
        additional_dependencies:
          - pytest
          - python-multipart
          - fastapi
          - httpx
          - pymilvus[milvus_lite]
          - openai
          - sentence_transformers
          - pymupdf
          - pymupdf4llm
